["OSPRODWin1.7.0"]
design_data_url = "https://autopatchos.zenlesszonezero.com/design_data/1.7_live/output_7932457_4150c91370/client/"
design_data_revision = "7932457"
design_data_files = '[{"fileName":"data_version","fileSize":4982,"fileMD5":"8734145110456791504"}]'
game_res_url = "https://autopatchos.zenlesszonezero.com/game_res/1.7_live/output_7932457_4150c91370/client/"
game_res_branch = "1.7_live"
game_audio_revision = "7932457"
game_res_revision = "7932457"
game_res_files = '[{"fileName":"res_version","fileSize":2525062,"fileMD5":"10941635733922406342"},{"fileName":"audio_version","fileSize":32267,"fileMD5":"13682458419733175648"},{"fileName":"base_revision","fileSize":18,"fileMD5":"3095416763157010707"}]'
silence_url = "https://autopatchos.zenlesszonezero.com/design_data/1.7_live/output_7932457_4150c91370/client_silence/"
silence_revision = "7932457"
silence_files = '[{"fileName":"silence_version","fileSize":647,"fileMD5":"18011241757663189513"}]'
